package main

import (
	cryptoRand "crypto/rand"
	"log/slog"
	"math/big"
	"net/http"
	"os"
	"time"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

// Prometheus metrics
var (
	// Counter for total log messages generated
	logMessagesTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "log_messages_total",
			Help: "Total number of log messages generated by level",
		},
		[]string{"level"},
	)

	// Histogram for log processing latency
	logLatencySeconds = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Name:    "log_latency_seconds",
			Help:    "Time taken to process and emit log messages",
			Buckets: prometheus.DefBuckets,
		},
	)

	// Gauge for simulated active connections
	activeConnections = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Name: "active_connections",
			Help: "Number of simulated active connections",
		},
	)

	// Counter for HTTP requests to metrics endpoint
	httpRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "http_requests_total",
			Help: "Total number of HTTP requests",
		},
		[]string{"path", "method"},
	)

	// Histogram for HTTP request duration
	httpRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "http_request_duration_seconds",
			Help:    "HTTP request duration in seconds",
			Buckets: []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
		},
		[]string{"path"},
	)

	// Counter for errors encountered
	errorsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "errors_total",
			Help: "Total number of errors encountered",
		},
		[]string{"type"},
	)
)

func init() {
	// Register all metrics with Prometheus
	prometheus.MustRegister(logMessagesTotal)
	prometheus.MustRegister(logLatencySeconds)
	prometheus.MustRegister(activeConnections)
	prometheus.MustRegister(httpRequestsTotal)
	prometheus.MustRegister(httpRequestDuration)
	prometheus.MustRegister(errorsTotal)
}

// metricsMiddleware wraps HTTP handlers to collect metrics
func metricsMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()

		next.ServeHTTP(w, r)

		duration := time.Since(start).Seconds()
		httpRequestDuration.WithLabelValues(r.URL.Path).Observe(duration)
		httpRequestsTotal.WithLabelValues(r.URL.Path, r.Method).Inc()
	})
}

// secureRandInt generates a cryptographically secure random integer in range [0, n)
func secureRandInt(n int) int {
	if n <= 0 {
		return 0
	}
	result, err := cryptoRand.Int(cryptoRand.Reader, big.NewInt(int64(n)))
	if err != nil {
		// Fallback to timestamp-based value if crypto/rand fails
		return int(time.Now().UnixNano() % int64(n))
	}
	return int(result.Int64())
}

func main() {
	// Configure JSON logger to stdout
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	slog.SetDefault(logger)

	// Start HTTP server for Prometheus metrics with proper timeouts
	go func() {
		mux := http.NewServeMux()
		mux.Handle("/metrics", promhttp.Handler())
		mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
			if _, err := w.Write([]byte("OK")); err != nil {
				logger.Error("Failed to write health response", "error", err)
			}
		})

		server := &http.Server{
			Addr:         ":8080",
			Handler:      metricsMiddleware(mux),
			ReadTimeout:  10 * time.Second,
			WriteTimeout: 10 * time.Second,
			IdleTimeout:  60 * time.Second,
		}

		logger.Info("Starting metrics server", "port", 8080)
		if err := server.ListenAndServe(); err != nil {
			logger.Error("Metrics server failed", "error", err)
			errorsTotal.WithLabelValues("metrics_server").Inc()
		}
	}()

	levels := []slog.Level{slog.LevelInfo, slog.LevelError, slog.LevelDebug}
	messages := []string{
		"User logged in",
		"Failed to connect to database",
		"Processing request",
		"Data validation failed",
		"Connection timeout",
		"Cache hit",
		"Cache miss",
		"Starting background job",
	}

	logger.Info("Starting log generator service", "version", "2.0.0")

	// Simulate varying connection counts
	connectionCount := 0

	for {
		// Simulate connection changes
		connectionChange := secureRandInt(10) - 5 // -5 to +5
		connectionCount += connectionChange
		if connectionCount < 0 {
			connectionCount = 0
		}
		activeConnections.Set(float64(connectionCount))

		// Measure log processing time
		start := time.Now()

		level := levels[secureRandInt(len(levels))]
		msg := messages[secureRandInt(len(messages))]

		// Add some extra contextual data randomly
		userID := secureRandInt(1000)
		latency := time.Duration(secureRandInt(500)) * time.Millisecond

		switch level {
		case slog.LevelInfo:
			logger.Info(msg, "user_id", userID, "latency", latency.String())
			logMessagesTotal.WithLabelValues("info").Inc()
		case slog.LevelError:
			logger.Error(msg, "user_id", userID, "error_code", secureRandInt(500)+500)
			logMessagesTotal.WithLabelValues("error").Inc()
			errorsTotal.WithLabelValues("application").Inc()
		case slog.LevelDebug:
			logger.Debug(msg, "user_id", userID, "details", "some internal details")
			logMessagesTotal.WithLabelValues("debug").Inc()
		}

		// Record processing latency
		processingTime := time.Since(start).Seconds()
		logLatencySeconds.Observe(processingTime)

		// Sleep between 0.5s and 2s
		sleepDuration := time.Duration(secureRandInt(1500)+500) * time.Millisecond
		time.Sleep(sleepDuration)
	}
}
