{
 "title": "Cloud LogQL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Simple log",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"log-generator\"}\n"
    }
   ]
  },
  {
   "title": "Log count (5 min Interval)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({app=\"log-generator\"} | json [$__interval]))"
    }
   ]
  },
  {
   "title": "ERROR level",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "{compose_service=\"log-generator\"} | json | level=\"ERROR\""
    }
   ]
  },
  {
   "title": "Timeout logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"log-generator\"} |= \"timeout\""
    }
   ]
  },
  {
   "title": "Count logs over time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"log-generator\"}[5m])\n"
    }
   ]
  }
 ]
}